### ISSUE TITLE
Channel question

### ISSUE THREAD

**Issue by KONGFPV** [geofrancis/SBUS-to-IBUS#1]
Hi mate do I need to set the number of sbus channels anywhere? I can’t get it to work! Using arduino nano
Tx pin wired to right port on hoverboard ibus connected to tx pin on nano
Sbus from crossfire connected to d3 pin
Ibus variant flashed with 14 channels config as default

**Comment by geofrancis** [comment]
I have never tested it with crossfire, I usually use it with a flight controller SBUS output.

It wont work if you connect it to a Y lead with more than one device. it needs a dedicated SBUS output.

how are you powering it? do you have 5v connected to raw or vcc?

**Comment by KONGFPV** [comment]
> I have never tested it with crossfire, I usually use it with a flight controller SBUS output.
> 
> It wont work if you connect it to a Y lead with more than one device. it needs a dedicated SBUS output.
> 
> how are you powering it? do you have 5v connected to raw or vcc?

Hey mate, powering via 5v pin,
Would this be the best way to get a 4wd platform running? Did you end up using your converter I. The end? I was following your build on the ardu forum it’s amazing

**Comment by geofrancis** [comment]
yes i use it for both my 4wd rover and 6wd rover using the SBUS output from a flight controller. are you sure you have your receiver set to SBUS and not CRSF?

**Comment by KONGFPV** [comment]
Yeah crsf rx definitely set to output sbus ch1
Are you available on messenger at all? Add me! Brady heathcote from Australia

**Comment by geofrancis** [comment]
do you have different receiver you can test?

**Comment by KONGFPV** [comment]
I do, by any chance do you know if the subs signal needs to be inverted or uninverted? Do you know if the hoverboard will detect the ibus signal without a working sbus input? I’m getting 4 beeps still

**Comment by geofrancis** [comment]
The adapter doesnt output anything unless it gets an SBUS frame, it uses standard SBUS, I ran it direct from a FRSKY X8R receiver SBUS port.


what channels do you have your outputs set to? the adapter is configured to use channel 1 and 2 for the motors.

**Comment by geofrancis** [comment]
what channel do you have your motors set to? the adapter is convigured to use servo out 1 and servo out 2 for left and right.

**Comment by KONGFPV** [comment]
I’m not getting any movement what so ever, my rx is set to output sbus on ch1, I notice the lights on the arduino nano are blinking before I connect my rx then they go solid, is this normal? Do I have to set the ibus output pin in your code?

**Comment by geofrancis** [comment]
if you connect USB serial to the arduino serial pins what do you get out?

**Comment by KONGFPV** [comment]
Do you have Facebook bro? It will be much easier to message on there, I’ll google how to connect usb serial now and have a look

**Comment by KONGFPV** [comment]
![Uploading IMG_1974.jpeg…]()

**Comment by geofrancis** [comment]
you didnt upload it

what arduino board are you using?

**Comment by KONGFPV** [comment]
![IMG_1975](https://github.com/geofrancis/SBUS-to-IBUS/assets/90841511/399c8f51-04cd-4dac-8896-3f71cd17bd77)

**Comment by geofrancis** [comment]
That looks like its working, I think its either firmware or wiring to your boards thats the issue.

**Comment by KONGFPV** [comment]
Did you connect the right short cable or the left long cable to ibus? Also if I added 100nf capacitors to the signal lines should I remove them?

**Comment by geofrancis** [comment]
it wont work with the capacitors, those are only for PWM input. I think it uses the right side by default.
![726c5e090a138d45cf986cc98cd9f466b3aeed1c](https://github.com/geofrancis/SBUS-to-IBUS/assets/5570278/edc36a5a-a4a2-418f-9a9a-236abbbe573f)

**Comment by KONGFPV** [comment]
Woohoo! Success! She works as soon as I removed the capacitors!!

**Comment by KONGFPV** [comment]
My next question would be can I just y the ibus lead to multiple controllers?

**Comment by geofrancis** [comment]
Yes you can split the ibus output between all the controllers.

**Comment by KONGFPV** [comment]
Awesome thanks so much for your help!
